name = "ComplexHermiteFct"
uuid = "0c63080c-9546-48d9-913a-8575c4379365"
authors = ["Clement Guillot <clement.guillot@enpc.fr>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
